version: '3.9'
# we'll keep the version for now to work in Compose and Swarm

services:
  db:
    image: postgres:10.0-alpine
    container_name: postgresDB
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    volumes:
      - /ComIT-Project/myquery.sql:/docker-entrypoint-initdb.d/initdb.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080   
