version: '3.9'
# we'll keep the version for now to work in Compose and Swarm

services:
  db1:
    image: postgres:10.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_db
    volumes:
      - ./Database/myquery.sql:/docker-entrypoint-initdb.d/initdb.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080   
